services:
  app:
    build: .
    container_name: laravel_app
    restart: unless-stopped
    ports:
      - "9000"  
    working_dir: /var/www
    volumes:
      - .:/var/www
      - /var/www/node_modules
    networks:
      - laravel_net
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: laravel_nginx
    restart: unless-stopped
    ports:
      - "80:80"  # Render espera que el servicio web escuche en el puerto 80
    volumes:
      - .:/var/www
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel_net
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: laravel_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"  # Puerto estándar de MySQL
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel_net

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin-car
    restart: unless-stopped
    ports:
      - "8607:80"
    environment:
      - PMA_HOST=db
      - UPLOAD_LIMIT=300M
    depends_on:
      - db
    networks:
      - laravel_net
      
networks:
  laravel_net:

volumes:
  db_data:
