version: '3.8'

services:
  app:
    build: .
    container_name: laravel_app
    restart: unless-stopped
    ports:
      - $PORT:$DOCKER_PORT
    working_dir: /var/www
    volumes:
      - .:/var/www
      - /var/www/node_modules
    networks:
      - laravel_net
    depends_on:
      - db


  nginx:
    image: nginx:latest
    container_name: laravel_nginx
    restart: unless-stopped
    ports:
      - $PORT_F:$DOCKER_PORT_F
    volumes:
      - .:/var/www
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel_net
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: laravel_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: $DB_DATABASE
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_USER: $DB_USERNAME
      MYSQL_PASSWORD: $DB_PASSWORD
    ports:
      - $MYSQLDB_DOCKER_PORT:$DB_PORT
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel_net

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin-car
    restart: unless-stopped
    ports:
      - 8607:80
    environment:
      - PMA_HOST=db
      - UPLOAD_LIMIT=300M
    depends_on:
      - db
    networks:
      - laravel_net
      
networks:
  laravel_net:

volumes:
  db_data:
